sudo: required
services:
  - docker

before_install:
  - docker build -t siddharthrajkumar/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true siddharthrajkumar/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Docker-react-env-2"
  bucket_name: "elasticbeanstalk-eu-north-1-839117473964"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"