name: Deploy Docker Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t siddharthrajkumar/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true siddharthrajkumar/docker-react-test npm test
